(source "elpy" "https://jorgenschaefer.github.io/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "tromey" "http://tromey.com/elpa/")
(source org)

(depends-on "all-the-icons")
(depends-on "async")
(depends-on "aurora-config-mode")
(depends-on "base16-theme")
(depends-on "cask")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "clojure-mode-extra-font-locking")
(depends-on "company")
(depends-on "dash")
(depends-on "doom-themes")
(depends-on "elpy")
(depends-on "epl")
(depends-on "exec-path-from-shell")
(depends-on "f")
(depends-on "find-file-in-project")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "flyspell-correct")
(depends-on "font-lock+")
(depends-on "git-commit")
(depends-on "highlight-indentation")
(depends-on "hlinum")
(depends-on "ido-completing-read+")
(depends-on "ido-ubiquitous")
(depends-on "ivy")
(depends-on "js2-mode")
(depends-on "jsx-mode")
(depends-on "magit")
(depends-on "magit-popup")
(depends-on "monokai-theme")
(depends-on "multi-web-mode")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "pkg-info")
(depends-on "projectile")
(depends-on "pyvenv")
(depends-on "queue")
(depends-on "rainbow-delimiters")
(depends-on "s")
(depends-on "seq")
(depends-on "shut-up")
(depends-on "smex")
(depends-on "smooth-scrolling")
(depends-on "spinner")
(depends-on "tagedit")
(depends-on "transpose-frame")
(depends-on "tt-mode")
(depends-on "web-mode")
(depends-on "with-editor")
(depends-on "yasnippet")
